name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  package_dpkg:
    name: Package for Debian/Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Print env vars
        run: printenv

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      # from here to 'start services' is a docker test suite to make 'make test' work
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      # need to do this before we start the services as they need the TLS creds
      - name: Create test certs for TLS
        run: |
          make test-certs
          chmod 777 ./contrib/tls/*

      - name: Start services
        run: docker-compose up -d
        working-directory: ./

      - name: Prep deps
        run: make build-dep

      - name: Build binaries
        run: make build

      - name: Build
        run: make dpkg

      - name: Upload dpkg
        uses: actions/upload-artifact@v4
        with:
          name: packages-dpkg
          path: "*.deb"
